# Documentation
# https://docs.gitlab.com/ee/ci/yaml/

stages:
- build
- deploy
- publish

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

build:
  stage: build
  image: node
  before_script:
    - apt update
    - apt install chromium -y
    - npm i
  script:
    - npm run lint
    - npm run build:lib
    - npm run test
    - npm run build
  artifacts:
    paths:
    - dist/password-checker-lib/
    - dist/example-app/
    expire_in: 1337 mins

deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "master"'
      when: on_success
    - if: '$CI_COMMIT_REF_SLUG == "develop"'
      when: on_success
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/password-checker-example-app:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

publish:
  stage: publish
  image: node
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "master"'
      when: on_success
  script:
      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>~/.npmrc
      - cd $CI_PROJECT_DIR/dist/password-checker-lib
      - npm publish --access public
      - rm -f ~/.npmrc
  after_script:
    - rm -f ~/.npmrc
